site: Lokesh Venkatesh
title: Lokesh Venkatesh
email: 
description: >-
  Personal academic website

baseurl: ""
url: "https://lokesh-venkatesh.github.io"

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Minima social links
minima:
  social_links:
    github: 
    twitter: 
    linkedin: 
    email: 

# Navigation
header_pages:
  - about.md
