site: Lokesh Venkatesh
title: Lokesh Venkatesh
email: lokesh.venkatesh@students.iiserpune.ac.in
description: >-
  Personal website

baseurl: ""
url: "https://lokesh-venkatesh.github.io"

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Minima social links
minima:
  social_links:
    github: https://github.com/lokesh-venkatesh/
    twitter: https://x.com/lokesh_v04
    linkedin: https://www.linkedin.com/in/venkatesh-lokesh/
    email: mailto:lokesh.venkatesh@students.iiserpune.ac.in

# Navigation
header_pages:
  - about.md
  - cv.md
